/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.org.assembleia.view;

import br.org.assembleia.control.CargosController;
import br.org.assembleia.control.MembroController;
import br.org.assembleia.model.CargosModel;
import br.org.assembleia.model.MembroModel;
import br.org.assembleia.model.PessoasModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class form_cad_membro extends javax.swing.JFrame {

    // ira manter os cargos que foram inicializados na combo
    // assim, ao inserir novo registro ou atualizar, basta capturar o id do objeto,
    // conforme seleção da posicao no combo
    private static List<CargosModel> listaCargos;

    // ira aarmazenar dados da pessoa selecionada, 
    private PessoasModel pessoaSelecionada = null;

    // armazena objeto de um membro selecionado na view localizar
    // para possivel alteracao ou desativacao de membro
    private MembroModel membroSelecionado = null;

    /**
     * Creates new form form_cad_membro
     */
    public form_cad_membro() {
        initComponents();
        CargosController controle = new CargosController();
        this.listaCargos = controle.getListaCargos();

        for (CargosModel listaCargo : listaCargos) {
            comboListaCargos.addItem(listaCargo.getCargo());
        }
    }

    /**
     * Preenche o campos referente ao membro que foi selecionado
     *
     * @param membro
     */
    private void preencerCamposMembro(MembroModel membro) {

        this.membroSelecionado = membro;
        campoNome.setText(membro.getNome());
        campoDataPosse.setText(membro.getDataPosse());
        // metodo que ira buscar o cargo selecionado para este membro
        getListaCargos(this.membroSelecionado.getIdCargo());

    }

    /**
     * Define o cargo de um determinado membro que foi recuperado da base de
     * dados, para atualizacao ou desativacao
     *
     * @param idCargo
     */
    private void getListaCargos(int idCargo) {

        CargosController controler = new CargosController();
        List<CargosModel> lista = controler.getListaCargos();

        for (CargosModel cargo : lista) {
            if (cargo.getIdentificador() == idCargo) {
                comboListaCargos.setSelectedItem(cargo.getCargo());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboListaCargos = new javax.swing.JComboBox<>();
        btnLocalizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoDataPosse = new javax.swing.JFormattedTextField();
        btnDesligarMembro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoDataDesligamento = new javax.swing.JFormattedTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnBuscarMembros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Membros");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/assembleia/imagens/icons8-conferência-96.png"))); // NOI18N
        jLabel17.setText("Cadastrar Membros/cargos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome:");

        jLabel2.setText("Cargo:");

        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/assembleia/imagens/icons8-pesquisar-mais-30.png"))); // NOI18N
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        jLabel3.setText("Data posse:");

        try {
            campoDataPosse.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnDesligarMembro.setText("Desligar membro");
        btnDesligarMembro.setEnabled(false);
        btnDesligarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesligarMembroActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Desligamento:");

        try {
            campoDataDesligamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDataDesligamento.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoDataDesligamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoDataDesligamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDesligarMembro)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboListaCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoDataPosse, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLocalizar)
                            .addGap(6, 6, 6))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboListaCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(campoDataPosse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnDesligarMembro)
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setFocusable(false);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/assembleia/imagens/icons8-salvar-e-fechar-48.png"))); // NOI18N
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvar);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/assembleia/imagens/icons8-vassoura-48.png"))); // NOI18N
        btnLimpar.setFocusable(false);
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpar);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/assembleia/imagens/icons8-reiniciar-48.png"))); // NOI18N
        btnAtualizar.setEnabled(false);
        btnAtualizar.setFocusable(false);
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAtualizar);

        btnBuscarMembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/org/assembleia/imagens/icons8-tarefa-de-grupo-48.png"))); // NOI18N
        btnBuscarMembros.setFocusable(false);
        btnBuscarMembros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarMembros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMembrosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuscarMembros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        if (campoNome.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Atenção preencha os campos NOME e DATA DE POSSE!", "Verifique", JOptionPane.ERROR_MESSAGE);
        } else {

            MembroModel membro = new MembroModel();
            membro.setId_pessoa(this.pessoaSelecionada.getId_pessoa());
            membro.setIdCargo(
                    this.listaCargos.get(
                            comboListaCargos.getSelectedIndex()).getIdentificador()
            );
            membro.setDataPosse(campoDataPosse.getText());

            MembroController controler = new MembroController();
            int retorno = controler.insertMembro(membro);

            if (retorno != 0) {
                JOptionPane.showMessageDialog(null, "Parabens... cadastro realizado com sucesso!!");
            }

        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        // TODO add your handling code here:
        form_localizar_pessoas buscarPessoa = new form_localizar_pessoas(this, true);
        buscarPessoa.setVisible(true);

        if (buscarPessoa.getPessoa != null) {
            this.pessoaSelecionada = buscarPessoa.getPessoa;
            campoNome.setText(pessoaSelecionada.getNome());
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnBuscarMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMembrosActionPerformed

        form_localizar_pessoas membro = new form_localizar_pessoas(this, true, "membro");
        membro.setVisible(true);

        if (membro.getMembro != null) {

            preencerCamposMembro(membro.getMembro);

            // ativa btnDesativar
            btnDesligarMembro.setEnabled(true);
            btnAtualizar.setEnabled(true);
            btnSalvar.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "Nenhum membro foi selecionado!");
        }
    }//GEN-LAST:event_btnBuscarMembrosActionPerformed

    private void btnDesligarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesligarMembroActionPerformed

        if (this.membroSelecionado != null) {

            // preenche o campo data de deslisgamento
            LocalDate dat = LocalDate.now();
            DateTimeFormatter frm = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            campoDataDesligamento.setText(frm.format(dat));


            // atualizada os dados para desligado
            MembroModel membro = new MembroModel();
            membro.setId(this.membroSelecionado.getId());
            membro.setId_pessoa(this.membroSelecionado.getId_pessoa());
            membro.setDataPosse(campoDataPosse.getText());
            membro.setIdCargo(this.membroSelecionado.getIdCargo());
            membro.setDataDemissao(dat.toString());
            membro.setSituacao("I");
            
            MembroController controler = new MembroController();
            int desativarMembro = controler.desativarMembro(membro);
            
            if(desativarMembro != 0){
                btnDesligarMembro.setEnabled(false);
                this.membroSelecionado = null;
                this.pessoaSelecionada = null;
                JOptionPane.showMessageDialog(this, "Este cadastro foi desativado!");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Ops...nenhum membro foi selecionado, verifique");
        }
    }//GEN-LAST:event_btnDesligarMembroActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        
        if (this.membroSelecionado != null) {

            // preenche o campo data de deslisgamento
            LocalDate dat = LocalDate.now();
            DateTimeFormatter frm = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            // atualizada os dados para desligado
            MembroModel membro = new MembroModel();
            membro.setId(this.membroSelecionado.getId());
            membro.setId_pessoa(this.pessoaSelecionada.getId_pessoa());
            membro.setDataPosse(campoDataPosse.getText());
            
            // recupera o cargo que esta selecionado, conforme combo
            membro.setIdCargo(listaCargos.get(
                    comboListaCargos.getSelectedIndex())
                    .getIdentificador());
            
            membro.setSituacao("A");
            
            MembroController controler = new MembroController();
            int updateMembro = controler.desativarMembro(membro);
            
            if(updateMembro != 0){
                this.membroSelecionado = null;
                this.pessoaSelecionada = null;
                JOptionPane.showMessageDialog(this, "Parabens cadastro atualizado com sucesso!");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Ops...nenhum membro foi selecionado, verifique");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        campoDataDesligamento.setText(null);
        campoDataPosse.setText(null);
        this.membroSelecionado = null;
        this.pessoaSelecionada = null;
        btnDesligarMembro.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnAtualizar.setEnabled(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_cad_membro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_cad_membro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_cad_membro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_cad_membro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_cad_membro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscarMembros;
    private javax.swing.JButton btnDesligarMembro;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField campoDataDesligamento;
    private javax.swing.JFormattedTextField campoDataPosse;
    private javax.swing.JTextField campoNome;
    private javax.swing.JComboBox<String> comboListaCargos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
